import '../globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
       
        <main style={{ minHeight: '80vh', padding: '2rem' }}>
          {children}
        </main>
        <footer style={{ padding: '1rem', background: '#222', color: '#fff', textAlign: 'center' }}>
          &copy; 2025 My App. All rights reserved.
        </footer>
      </body>
    </html>
  )
}
