import '../globals.css'

import { Metadata } from 'next'
import LoadingIndicator from '../ui/loading-indicator'

import LocaleSwitcher from '../ui/locale-switcher'

export const metadata: Metadata = {
  title: 'Next.js App',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col p-6">
        {/* Optional: global loading indicator */}
        <LoadingIndicator slug="loading" title="Loading..." />

        {/* Locale switcher visible on all pages */}
        <div className="mb-4">
          <LocaleSwitcher />
        </div>

        {/* Page content */}
        <main className="flex-1">{children}</main>
      </body>
    </html>
  )
}
