import './globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ padding: '1rem', background: '#222', color: '#fff' }}>
          <nav>
            <h1 style={{ margin: 0 }}>My App</h1>
            {/* Add navigation links here */}
          </nav>
        </header>
        <main style={{ minHeight: '80vh', padding: '2rem' }}>
          {children}
        </main>
        <footer style={{ padding: '1rem', background: '#222', color: '#fff', textAlign: 'center' }}>
          &copy; 2025 My App. All rights reserved.
        </footer>
      </body>
    </html>
  )
}
